export default {
  info: {
    statuscode: 0,
    copyright: {
      text: "© 2020 MapQuest, Inc.",
      imageUrl: "http://api.mqcdn.com/res/mqlogo.gif",
      imageAltText: "© 2020 MapQuest, Inc.",
    },
    messages: [],
  },
  options: {
    maxResults: -1,
    thumbMaps: false,
    ignoreLatLngInput: false,
  },
  results: [
    {
      providedLocation: {
        location: "London",
      },
      locations: [
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Westminster",
          adminArea4Type: "County",
          adminArea3: "",
          adminArea3Type: "State",
          adminArea1: "GB",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282415113",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 51.507276,
            lng: -0.12766,
          },
          displayLatLng: {
            lat: 51.507276,
            lng: -0.12766,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Middlesex",
          adminArea4Type: "County",
          adminArea3: "ON",
          adminArea3Type: "State",
          adminArea1: "CA",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282177353",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 42.984267,
            lng: -81.247534,
          },
          displayLatLng: {
            lat: 42.984267,
            lng: -81.247534,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Laurel County",
          adminArea4Type: "County",
          adminArea3: "KY",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282031710",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 37.128849,
            lng: -84.083677,
          },
          displayLatLng: {
            lat: 37.128849,
            lng: -84.083677,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Dane County",
          adminArea4Type: "County",
          adminArea3: "WI",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283443777",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 43.047798,
            lng: -89.012802,
          },
          displayLatLng: {
            lat: 43.047798,
            lng: -89.012802,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Madison County",
          adminArea4Type: "County",
          adminArea3: "OH",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282023712",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 39.889837,
            lng: -83.440621,
          },
          displayLatLng: {
            lat: 39.889837,
            lng: -83.440621,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Tulare County",
          adminArea4Type: "County",
          adminArea3: "CA",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282087933",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 36.480647,
            lng: -119.442838,
          },
          displayLatLng: {
            lat: 36.480647,
            lng: -119.442838,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Pope County",
          adminArea4Type: "County",
          adminArea3: "AR",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282025198",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 35.330799,
            lng: -93.247163,
          },
          displayLatLng: {
            lat: 35.330799,
            lng: -93.247163,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Kanawha County",
          adminArea4Type: "County",
          adminArea3: "WV",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283508638",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 38.194401,
            lng: -81.368896,
          },
          displayLatLng: {
            lat: 38.194401,
            lng: -81.368896,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Monroe County",
          adminArea4Type: "County",
          adminArea3: "MI",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283486611",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 42.029514,
            lng: -83.615771,
          },
          displayLatLng: {
            lat: 42.029514,
            lng: -83.615771,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Freeborn County",
          adminArea4Type: "County",
          adminArea3: "MN",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282916815",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 43.526891,
            lng: -93.063727,
          },
          displayLatLng: {
            lat: 43.526891,
            lng: -93.063727,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Lane County",
          adminArea4Type: "County",
          adminArea3: "OR",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282896269",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 43.634701,
            lng: -123.091698,
          },
          displayLatLng: {
            lat: 43.634701,
            lng: -123.091698,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "",
          adminArea5Type: "City",
          adminArea4: "City of London",
          adminArea4Type: "County",
          adminArea3: "",
          adminArea3Type: "State",
          adminArea1: "GB",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A4XAX",
          geocodeQuality: "COUNTY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "360171791",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 51.514511,
            lng: -0.089215,
          },
          displayLatLng: {
            lat: 51.514511,
            lng: -0.089215,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Kimble County",
          adminArea4Type: "County",
          adminArea3: "TX",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "282925392",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 30.676701,
            lng: -99.576103,
          },
          displayLatLng: {
            lat: 30.676701,
            lng: -99.576103,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Mercer County",
          adminArea4Type: "County",
          adminArea3: "PA",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283497120",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 41.1436,
            lng: -80.148903,
          },
          displayLatLng: {
            lat: 41.1436,
            lng: -80.148903,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Conecuh County",
          adminArea4Type: "County",
          adminArea3: "AL",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283493822",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 31.297501,
            lng: -87.087799,
          },
          displayLatLng: {
            lat: 31.297501,
            lng: -87.087799,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Lake County",
          adminArea4Type: "County",
          adminArea3: "MN",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283482740",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 47.202801,
            lng: -91.569397,
          },
          displayLatLng: {
            lat: 47.202801,
            lng: -91.569397,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Montgomery County",
          adminArea4Type: "County",
          adminArea3: "AL",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283445311",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 32.273102,
            lng: -86.050301,
          },
          displayLatLng: {
            lat: 32.273102,
            lng: -86.050301,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Cocke County",
          adminArea4Type: "County",
          adminArea3: "TN",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283440952",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 35.869701,
            lng: -83.002197,
          },
          displayLatLng: {
            lat: 35.869701,
            lng: -83.002197,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Shelby County",
          adminArea4Type: "County",
          adminArea3: "IN",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "283435392",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 39.625599,
            lng: -85.920303,
          },
          displayLatLng: {
            lat: 39.625599,
            lng: -85.920303,
          },
        },
        {
          street: "",
          adminArea6: "",
          adminArea6Type: "Neighborhood",
          adminArea5: "London",
          adminArea5Type: "City",
          adminArea4: "Sumner County",
          adminArea4Type: "County",
          adminArea3: "KS",
          adminArea3Type: "State",
          adminArea1: "US",
          adminArea1Type: "Country",
          postalCode: "",
          geocodeQualityCode: "A5XAX",
          geocodeQuality: "CITY",
          dragPoint: false,
          sideOfStreet: "N",
          linkId: "364488951",
          unknownInput: "",
          type: "s",
          latLng: {
            lat: 37.476085,
            lng: -97.371584,
          },
          displayLatLng: {
            lat: 37.476085,
            lng: -97.371584,
          },
        },
      ],
    },
  ],
};
